baseURL = "https://lbmcu.github.io"
languageCode = "zh-cn"
title = "Nolan's Blog"
theme = "stack"

[pagination]
  pagerSize = 6

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["plc", "embedded", "linux", "notes"]