[sidebar]
  subtitle = "PLC & Embedded Systems Engineer"
  avatar = "/img/avatar.png"

[article]
  readingTime = true
  toc = true

[footer]
  since = 2026

[widgets]
  homepage = [
    { type = "search" },
    { type = "archives" },
    { type = "categories" },
    { type = "tag-cloud" }
  ]

[colorScheme]
  toggle = true
  default = "auto"

[opengraph]
  enable = false